name: seon_sdk_flutter_plugin
description: "SEON SDK Flutter Plugin"
version: 1.0.0
homepage: https://seon.io

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
flutter:
  plugin:
    platforms:
      android:
        package: io.seon.seon_sdk_flutter_plugin
        pluginClass: SeonSdkFlutterPlugin
      ios:
        pluginClass: SeonSdkFlutterPlugin
