name: Validate flutter package
run-name: Validating flutter package 🚀
on: [push]
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
      - name: Run flutter package check      
        run: flutter pub pub publish --dry-run
